-- KitchenMind — ingredient alias seed
-- Safe to run multiple times: upserts on alias_name

insert into ingredient_aliases (alias_name, canonical_name) values
  -- ── Salt ──────────────────────────────────────────────────
  ('TATA SALT',              'Salt'),
  ('TATA SALT 1KG',          'Salt'),
  ('TATA SALT 2KG',          'Salt'),
  ('ROCK SALT',              'Salt'),
  ('SENDHA NAMAK',           'Rock Salt'),
  ('IODISED SALT',           'Salt'),

  -- ── Cooking Oil ───────────────────────────────────────────
  ('FORTUNE OIL',            'Cooking Oil'),
  ('FORTUNE SUNFLWR OIL',    'Cooking Oil'),
  ('FORTUNE SUNFLOWER OIL',  'Cooking Oil'),
  ('SAFFOLA OIL',            'Cooking Oil'),
  ('SAFFOLA GOLD',           'Cooking Oil'),
  ('SUNDROP OIL',            'Cooking Oil'),
  ('DHARA OIL',              'Cooking Oil'),
  ('EMAMI HEALTHY LITE',     'Cooking Oil'),
  ('MUSTARD OIL',            'Mustard Oil'),
  ('PATANJALI MUSTARD OIL',  'Mustard Oil'),

  -- ── Wheat Flour ───────────────────────────────────────────
  ('AASHIRVAAD ATTA',        'Wheat Flour'),
  ('AASHIRVAAD ATT',         'Wheat Flour'),
  ('AASHIRVAD ATTA',         'Wheat Flour'),
  ('PILSBURY ATTA',          'Wheat Flour'),
  ('PILLSBURY ATTA',         'Wheat Flour'),
  ('ANNAPURNA ATTA',         'Wheat Flour'),
  ('SHAKTI BHOG ATTA',       'Wheat Flour'),
  ('PATANJALI ATTA',         'Wheat Flour'),

  -- ── Rice ──────────────────────────────────────────────────
  ('INDIA GATE RICE',        'Basmati Rice'),
  ('INDIA GATE BASMATI',     'Basmati Rice'),
  ('KOHINOOR RICE',          'Basmati Rice'),
  ('KOHINOOR BASMATI',       'Basmati Rice'),
  ('DAAWAT RICE',            'Basmati Rice'),
  ('DAAWAT BASMATI',         'Basmati Rice'),
  ('DAWAT RICE',             'Basmati Rice'),
  ('LAXMI BOMB RICE',        'Rice'),
  ('SONA MASOORI RICE',      'Rice'),

  -- ── Dal ───────────────────────────────────────────────────
  ('MASOOR DAL',             'Masoor Dal'),
  ('MASUR DAL',              'Masoor Dal'),
  ('TOOR DAL',               'Toor Dal'),
  ('TUR DAL',                'Toor Dal'),
  ('ARHAR DAL',              'Toor Dal'),
  ('MOONG DAL',              'Moong Dal'),
  ('MUNG DAL',               'Moong Dal'),
  ('CHANA DAL',              'Chana Dal'),
  ('URAD DAL',               'Urad Dal'),
  ('URAD DAL WHOLE',         'Urad Dal'),
  ('RAJMA',                  'Kidney Beans'),
  ('KABULI CHANA',           'Chickpeas'),
  ('CHOLE',                  'Chickpeas'),

  -- ── Flour & Grains ────────────────────────────────────────
  ('BESAN',                  'Gram Flour'),
  ('GRAM FLOUR',             'Gram Flour'),
  ('MAIDA',                  'Refined Flour'),
  ('SOOJI',                  'Semolina'),
  ('SUJI',                   'Semolina'),
  ('RAVA',                   'Semolina'),
  ('POHA',                   'Flattened Rice'),
  ('SABUDANA',               'Tapioca Pearls'),

  -- ── Spices ────────────────────────────────────────────────
  ('MDH CHILLI PWD',         'Red Chilli Powder'),
  ('MDH LALMIRCH',           'Red Chilli Powder'),
  ('MDH HALDI',              'Turmeric'),
  ('MDH TURMERIC',           'Turmeric'),
  ('EVEREST GARAM MSL',      'Garam Masala'),
  ('EVEREST GARAM MASALA',   'Garam Masala'),
  ('MDH GARAM MASALA',       'Garam Masala'),
  ('EVEREST CHILLI PWD',     'Red Chilli Powder'),
  ('CATCH PEPPER',           'Black Pepper'),
  ('MDH DHANIYA',            'Coriander Powder'),
  ('JEERA',                  'Cumin'),
  ('MDH JEERA',              'Cumin'),
  ('HING',                   'Asafoetida'),
  ('ASAFOETIDA',             'Asafoetida'),
  ('PATANJALI HALDI',        'Turmeric'),

  -- ── Dairy ─────────────────────────────────────────────────
  ('AMUL BUTTER',            'Butter'),
  ('AMUL MILK',              'Milk'),
  ('MOTHER DAIRY MILK',      'Milk'),
  ('NESTLE MILK',            'Milk'),
  ('GO MILK',                'Milk'),
  ('AMUL GHEE',              'Ghee'),
  ('PATANJALI GHEE',         'Ghee'),
  ('DESI GHEE',              'Ghee'),
  ('AMUL PANEER',            'Paneer'),
  ('MOTHER DAIRY PANEER',    'Paneer'),
  ('AMUL CURD',              'Curd'),
  ('MOTHER DAIRY CURD',      'Curd'),
  ('AMUL DAHI',              'Curd'),

  -- ── Bread & Noodles ───────────────────────────────────────
  ('BRITANNIA BREAD',        'Bread'),
  ('MODERN BREAD',           'Bread'),
  ('HARVEST GOLD BREAD',     'Bread'),
  ('MAGGI NOODLES',          'Noodles'),
  ('MAGGI 2MIN',             'Noodles'),
  ('YIPPEE NOODLES',         'Noodles'),
  ('PATANJALI NOODLES',      'Noodles'),

  -- ── Sugar & Sweeteners ────────────────────────────────────
  ('CHINI',                  'Sugar'),
  ('SUGAR',                  'Sugar'),
  ('CHEENI',                 'Sugar'),
  ('SHAKKAR',                'Sugar'),
  ('PATANJALI SHAKKAR',      'Jaggery Powder'),
  ('GUR',                    'Jaggery'),
  ('JAGGERY',                'Jaggery'),

  -- ── Vegetables (as they appear on bills) ──────────────────
  ('ALOO',                   'Potato'),
  ('POTATO',                 'Potato'),
  ('PYAZ',                   'Onion'),
  ('ONION',                  'Onion'),
  ('TAMATAR',                'Tomato'),
  ('TOMATO',                 'Tomato'),
  ('ADRAK',                  'Ginger'),
  ('GINGER',                 'Ginger'),
  ('LAHSUN',                 'Garlic'),
  ('GARLIC',                 'Garlic'),
  ('MIRCH',                  'Green Chilli'),
  ('HARI MIRCH',             'Green Chilli'),
  ('GREEN CHILLI',           'Green Chilli'),
  ('PALAK',                  'Spinach'),
  ('SPINACH',                'Spinach'),
  ('METHI',                  'Fenugreek Leaves'),
  ('GOBI',                   'Cauliflower'),
  ('PHOOL GOBI',             'Cauliflower'),
  ('CAULIFLOWER',            'Cauliflower'),
  ('MATAR',                  'Green Peas'),
  ('GREEN PEAS',             'Green Peas'),
  ('BHINDI',                 'Okra'),
  ('OKRA',                   'Okra'),
  ('BAINGAN',                'Brinjal'),
  ('BRINJAL',                'Brinjal'),
  ('EGGPLANT',               'Brinjal'),
  ('LAUKI',                  'Bottle Gourd'),
  ('TORI',                   'Ridge Gourd'),
  ('KARELA',                 'Bitter Gourd'),
  ('SHIMLA MIRCH',           'Capsicum'),
  ('CAPSICUM',               'Capsicum'),
  ('GAJAR',                  'Carrot'),
  ('CARROT',                 'Carrot'),
  ('MULI',                   'Radish'),
  ('MOOLI',                  'Radish'),
  ('ARBI',                   'Taro Root'),
  ('KELA',                   'Banana'),
  ('BANANA',                 'Banana'),
  ('DHANIYA',                'Coriander'),
  ('CORIANDER',              'Coriander'),
  ('PODINA',                 'Mint'),
  ('MINT',                   'Mint')

on conflict (alias_name) do update
  set canonical_name = excluded.canonical_name;
