-- KitchenMind — inventory / add-item alias seed
-- Maps Hindi/colloquial names to canonical names used in inventory table
-- Safe to re-run: upserts on alias_name

insert into ingredient_aliases (alias_name, canonical_name) values
  -- ── Staples ───────────────────────────────────────────────
  ('Rice',              'Rice'),
  ('Chawal',            'Rice'),
  ('Atta',              'Wheat Flour'),
  ('Gehun ka atta',     'Wheat Flour'),
  ('Gehun atta',        'Wheat Flour'),
  ('Maida',             'Refined Flour'),
  ('Besan',             'Gram Flour'),
  ('Gram Flour',        'Gram Flour'),
  ('Sooji',             'Semolina'),
  ('Suji',              'Semolina'),
  ('Rava',              'Semolina'),
  ('Chini',             'Sugar'),
  ('Cheeni',            'Sugar'),
  ('Shakkar',           'Sugar'),
  ('Namak',             'Salt'),
  ('Tel',               'Cooking Oil'),
  ('Sarson ka tel',     'Mustard Oil'),
  ('Ghee',              'Ghee'),
  ('Desi ghee',         'Ghee'),
  ('Rajma',             'Kidney Beans'),
  ('Kidney Beans',      'Kidney Beans'),
  ('Kabuli chana',      'Chickpeas'),
  ('Chole',             'Chickpeas'),
  ('Poha',              'Flattened Rice'),
  ('Chivda',            'Flattened Rice'),
  ('Sabudana',          'Tapioca Pearls'),
  ('Sago',              'Tapioca Pearls'),
  ('Seviyan',           'Vermicelli'),
  ('Semiya',            'Vermicelli'),

  -- ── Fresh & Vegetables ────────────────────────────────────
  ('Aloo',              'Potato'),
  ('Alu',               'Potato'),
  ('Potato',            'Potato'),
  ('Pyaz',              'Onion'),
  ('Pyaaz',             'Onion'),
  ('Onion',             'Onion'),
  ('Tamatar',           'Tomato'),
  ('Tomato',            'Tomato'),
  ('Adrak',             'Ginger'),
  ('Ginger',            'Ginger'),
  ('Lahsun',            'Garlic'),
  ('Lasan',             'Garlic'),
  ('Garlic',            'Garlic'),
  ('Hari mirch',        'Green Chilli'),
  ('Mirch',             'Green Chilli'),
  ('Green Chilli',      'Green Chilli'),
  ('Palak',             'Spinach'),
  ('Spinach',           'Spinach'),
  ('Methi',             'Fenugreek Leaves'),
  ('Fenugreek Leaves',  'Fenugreek Leaves'),
  ('Gobi',              'Cauliflower'),
  ('Phool gobi',        'Cauliflower'),
  ('Cauliflower',       'Cauliflower'),
  ('Matar',             'Green Peas'),
  ('Green Peas',        'Green Peas'),
  ('Bhindi',            'Okra'),
  ('Okra',              'Okra'),
  ('Baingan',           'Brinjal'),
  ('Begun',             'Brinjal'),
  ('Brinjal',           'Brinjal'),
  ('Lauki',             'Bottle Gourd'),
  ('Dudhi',             'Bottle Gourd'),
  ('Bottle Gourd',      'Bottle Gourd'),
  ('Tori',              'Ridge Gourd'),
  ('Ridge Gourd',       'Ridge Gourd'),
  ('Karela',            'Bitter Gourd'),
  ('Bitter Gourd',      'Bitter Gourd'),
  ('Patta gobi',        'Cabbage'),
  ('Band gobi',         'Cabbage'),
  ('Cabbage',           'Cabbage'),
  ('Gajar',             'Carrot'),
  ('Carrot',            'Carrot'),
  ('Sem',               'Beans'),
  ('Beans',             'Beans'),
  ('Shimla mirch',      'Capsicum'),
  ('Capsicum',          'Capsicum'),
  ('Bell pepper',       'Capsicum'),
  ('Sahjan',            'Drumstick'),
  ('Drumstick',         'Drumstick'),
  ('Kela',              'Raw Banana'),
  ('Raw Banana',        'Raw Banana'),
  ('Kaddu',             'Pumpkin'),
  ('Pumpkin',           'Pumpkin'),
  ('Arbi',              'Colocasia'),
  ('Taro root',         'Colocasia'),
  ('Parwal',            'Pointed Gourd'),
  ('Pointed Gourd',     'Pointed Gourd'),
  ('Khumb',             'Mushroom'),
  ('Mushroom',          'Mushroom'),
  ('Makka',             'Corn'),
  ('Corn',              'Corn'),
  ('Bhutta',            'Corn'),
  ('Kheera',            'Cucumber'),
  ('Cucumber',          'Cucumber'),
  ('Dhaniya patti',     'Coriander Leaves'),
  ('Hara dhaniya',      'Coriander Leaves'),
  ('Coriander Leaves',  'Coriander Leaves'),
  ('Kadi patta',        'Curry Leaves'),
  ('Curry Leaves',      'Curry Leaves'),
  ('Pudina',            'Mint Leaves'),
  ('Podina',            'Mint Leaves'),
  ('Mint Leaves',       'Mint Leaves'),

  -- ── Dairy ─────────────────────────────────────────────────
  ('Doodh',             'Milk'),
  ('Milk',              'Milk'),
  ('Dahi',              'Curd'),
  ('Curd',              'Curd'),
  ('Yogurt',            'Curd'),
  ('Paneer',            'Paneer'),
  ('Cottage Cheese',    'Paneer'),
  ('Makhan',            'Butter'),
  ('Butter',            'Butter'),
  ('Cheese',            'Cheese'),
  ('Cream',             'Cream'),
  ('Malai',             'Cream'),
  ('Mawa',              'Khoya'),
  ('Khoya',             'Khoya'),
  ('Condensed Milk',    'Condensed Milk'),
  ('Milkmaid',          'Condensed Milk'),

  -- ── Non-Veg ───────────────────────────────────────────────
  ('Murgh',             'Chicken'),
  ('Chicken',           'Chicken'),
  ('Gosht',             'Mutton'),
  ('Mutton',            'Mutton'),
  ('Lamb',              'Mutton'),
  ('Machli',            'Fish'),
  ('Fish',              'Fish'),
  ('Jhinga',            'Prawns'),
  ('Prawns',            'Prawns'),
  ('Shrimp',            'Prawns'),
  ('Anda',              'Eggs'),
  ('Ande',              'Eggs'),
  ('Eggs',              'Eggs'),

  -- ── Spices ────────────────────────────────────────────────
  ('Haldi',             'Turmeric'),
  ('Turmeric',          'Turmeric'),
  ('Lal mirch',         'Red Chilli Powder'),
  ('Red Chilli Powder', 'Red Chilli Powder'),
  ('Dhaniya powder',    'Coriander Powder'),
  ('Coriander Powder',  'Coriander Powder'),
  ('Jeera',             'Cumin Seeds'),
  ('Cumin Seeds',       'Cumin Seeds'),
  ('Rai',               'Mustard Seeds'),
  ('Sarson',            'Mustard Seeds'),
  ('Mustard Seeds',     'Mustard Seeds'),
  ('Hing',              'Hing (Asafoetida)'),
  ('Asafoetida',        'Hing (Asafoetida)'),
  ('Kasuri methi',      'Kasuri Methi'),
  ('Kali mirch',        'Black Pepper'),
  ('Black Pepper',      'Black Pepper'),
  ('Elaichi',           'Cardamom'),
  ('Cardamom',          'Cardamom'),
  ('Laung',             'Cloves'),
  ('Cloves',            'Cloves'),
  ('Dalchini',          'Cinnamon'),
  ('Cinnamon',          'Cinnamon'),
  ('Tejpatta',          'Bay Leaves'),
  ('Bay Leaves',        'Bay Leaves'),
  ('Chakri phool',      'Star Anise'),
  ('Star Anise',        'Star Anise'),
  ('Saunf',             'Fennel Seeds'),
  ('Fennel Seeds',      'Fennel Seeds'),
  ('Ajwain',            'Carom Seeds (Ajwain)'),
  ('Carom Seeds',       'Carom Seeds (Ajwain)'),
  ('Methi dana',        'Fenugreek Seeds'),
  ('Fenugreek Seeds',   'Fenugreek Seeds'),
  ('Sukhi lal mirch',   'Dry Red Chilli'),
  ('Dry Red Chilli',    'Dry Red Chilli'),
  ('Imli',              'Tamarind'),
  ('Tamarind',          'Tamarind'),
  ('Amchur',            'Amchur (Dry Mango Powder)'),
  ('Chaat Masala',      'Chaat Masala'),
  ('Sambhar Masala',    'Sambhar Masala'),
  ('Pav Bhaji Masala',  'Pav Bhaji Masala'),
  ('Garam Masala',      'Garam Masala')

on conflict (alias_name) do update
  set canonical_name = excluded.canonical_name;
