// Curated Indian kitchen ingredient list — canonical_name values here MUST match what
// AddItem.jsx writes to inventory.canonical_name, since Recipe Workspace ingredient
// availability matching (src/utils/ingredientAvailability.js) is a case-insensitive
// canonical_name lookup. Single source of truth shared by AddItem and the Recipe Editor.
export const CURATED_INGREDIENTS = [
  // Staples
  { label: 'Rice',                canonical: 'Rice',                    category: 'Staples'            },
  { label: 'Wheat Flour (Atta)',   canonical: 'Wheat Flour',             category: 'Staples'            },
  { label: 'Refined Flour (Maida)',canonical: 'Refined Flour',           category: 'Staples'            },
  { label: 'Semolina (Sooji)',     canonical: 'Semolina',                category: 'Staples'            },
  { label: 'Gram Flour (Besan)',   canonical: 'Gram Flour',              category: 'Staples'            },
  { label: 'Sugar',               canonical: 'Sugar',                   category: 'Staples'            },
  { label: 'Salt',                canonical: 'Salt',                    category: 'Staples'            },
  { label: 'Cooking Oil',         canonical: 'Cooking Oil',             category: 'Staples'            },
  { label: 'Mustard Oil',         canonical: 'Mustard Oil',             category: 'Staples'            },
  { label: 'Ghee',                canonical: 'Ghee',                    category: 'Staples'            },
  { label: 'Masoor Dal',          canonical: 'Masoor Dal',              category: 'Staples'            },
  { label: 'Toor Dal',            canonical: 'Toor Dal',                category: 'Staples'            },
  { label: 'Moong Dal',           canonical: 'Moong Dal',               category: 'Staples'            },
  { label: 'Chana Dal',           canonical: 'Chana Dal',               category: 'Staples'            },
  { label: 'Urad Dal',            canonical: 'Urad Dal',                category: 'Staples'            },
  { label: 'Rajma',               canonical: 'Kidney Beans',            category: 'Staples'            },
  { label: 'Chickpeas (Chole)',    canonical: 'Chickpeas',               category: 'Staples'            },
  { label: 'Poha',                canonical: 'Flattened Rice',          category: 'Staples'            },
  { label: 'Sabudana',            canonical: 'Tapioca Pearls',          category: 'Staples'            },
  { label: 'Vermicelli (Seviyan)',  canonical: 'Vermicelli',             category: 'Staples'            },
  // Fresh & Vegetables
  { label: 'Potato',              canonical: 'Potato',                  category: 'Fresh & Vegetables' },
  { label: 'Onion',               canonical: 'Onion',                   category: 'Fresh & Vegetables' },
  { label: 'Tomato',              canonical: 'Tomato',                  category: 'Fresh & Vegetables' },
  { label: 'Ginger',              canonical: 'Ginger',                  category: 'Fresh & Vegetables' },
  { label: 'Garlic',              canonical: 'Garlic',                  category: 'Fresh & Vegetables' },
  { label: 'Green Chilli',        canonical: 'Green Chilli',            category: 'Fresh & Vegetables' },
  { label: 'Spinach (Palak)',     canonical: 'Spinach',                 category: 'Fresh & Vegetables' },
  { label: 'Fenugreek Leaves',    canonical: 'Fenugreek Leaves',        category: 'Fresh & Vegetables' },
  { label: 'Cauliflower (Gobi)',   canonical: 'Cauliflower',             category: 'Fresh & Vegetables' },
  { label: 'Green Peas (Matar)',  canonical: 'Green Peas',              category: 'Fresh & Vegetables' },
  { label: 'Okra (Bhindi)',       canonical: 'Okra',                    category: 'Fresh & Vegetables' },
  { label: 'Brinjal (Baingan)',   canonical: 'Brinjal',                 category: 'Fresh & Vegetables' },
  { label: 'Bottle Gourd (Lauki)',canonical: 'Bottle Gourd',            category: 'Fresh & Vegetables' },
  { label: 'Ridge Gourd (Tori)',  canonical: 'Ridge Gourd',             category: 'Fresh & Vegetables' },
  { label: 'Bitter Gourd (Karela)',canonical:'Bitter Gourd',            category: 'Fresh & Vegetables' },
  { label: 'Cabbage',             canonical: 'Cabbage',                 category: 'Fresh & Vegetables' },
  { label: 'Carrot (Gajar)',      canonical: 'Carrot',                  category: 'Fresh & Vegetables' },
  { label: 'Beans (Sem)',         canonical: 'Beans',                   category: 'Fresh & Vegetables' },
  { label: 'Capsicum',            canonical: 'Capsicum',                category: 'Fresh & Vegetables' },
  { label: 'Drumstick (Sahjan)',  canonical: 'Drumstick',               category: 'Fresh & Vegetables' },
  { label: 'Raw Banana (Kela)',   canonical: 'Raw Banana',              category: 'Fresh & Vegetables' },
  { label: 'Pumpkin (Kaddu)',     canonical: 'Pumpkin',                 category: 'Fresh & Vegetables' },
  { label: 'Colocasia (Arbi)',    canonical: 'Colocasia',               category: 'Fresh & Vegetables' },
  { label: 'Pointed Gourd (Parwal)',canonical:'Pointed Gourd',          category: 'Fresh & Vegetables' },
  { label: 'Mushroom',            canonical: 'Mushroom',                category: 'Fresh & Vegetables' },
  { label: 'Corn (Makka)',        canonical: 'Corn',                    category: 'Fresh & Vegetables' },
  { label: 'Cucumber (Kheera)',   canonical: 'Cucumber',                category: 'Fresh & Vegetables' },
  { label: 'Coriander Leaves',    canonical: 'Coriander Leaves',        category: 'Fresh & Vegetables' },
  { label: 'Curry Leaves',        canonical: 'Curry Leaves',            category: 'Fresh & Vegetables' },
  { label: 'Mint Leaves (Pudina)',canonical: 'Mint Leaves',             category: 'Fresh & Vegetables' },
  // Dairy
  { label: 'Milk',                canonical: 'Milk',                    category: 'Dairy'              },
  { label: 'Curd (Dahi)',         canonical: 'Curd',                    category: 'Dairy'              },
  { label: 'Paneer',              canonical: 'Paneer',                  category: 'Dairy'              },
  { label: 'Butter',              canonical: 'Butter',                  category: 'Dairy'              },
  { label: 'Cheese',              canonical: 'Cheese',                  category: 'Dairy'              },
  { label: 'Cream',               canonical: 'Cream',                   category: 'Dairy'              },
  { label: 'Khoya (Mawa)',        canonical: 'Khoya',                   category: 'Dairy'              },
  { label: 'Condensed Milk',      canonical: 'Condensed Milk',          category: 'Dairy'              },
  // Non-Veg
  { label: 'Chicken',             canonical: 'Chicken',                 category: 'Non-Veg'            },
  { label: 'Mutton / Goat',       canonical: 'Mutton',                  category: 'Non-Veg'            },
  { label: 'Fish',                canonical: 'Fish',                    category: 'Non-Veg'            },
  { label: 'Prawns',              canonical: 'Prawns',                  category: 'Non-Veg'            },
  { label: 'Eggs (Ande)',         canonical: 'Eggs',                    category: 'Non-Veg', isEggs: true },
  // Spices
  { label: 'Turmeric (Haldi)',    canonical: 'Turmeric',                category: 'Spices'             },
  { label: 'Red Chilli Powder',   canonical: 'Red Chilli Powder',       category: 'Spices'             },
  { label: 'Coriander Powder',    canonical: 'Coriander Powder',        category: 'Spices'             },
  { label: 'Cumin Seeds (Jeera)', canonical: 'Cumin Seeds',             category: 'Spices'             },
  { label: 'Mustard Seeds (Rai)', canonical: 'Mustard Seeds',           category: 'Spices'             },
  { label: 'Garam Masala',        canonical: 'Garam Masala',            category: 'Spices'             },
  { label: 'Hing (Asafoetida)',   canonical: 'Hing (Asafoetida)',       category: 'Spices'             },
  { label: 'Kasuri Methi',        canonical: 'Kasuri Methi',            category: 'Spices'             },
  { label: 'Black Pepper',        canonical: 'Black Pepper',            category: 'Spices'             },
  { label: 'Cardamom (Elaichi)',  canonical: 'Cardamom',                category: 'Spices'             },
  { label: 'Cloves (Laung)',      canonical: 'Cloves',                  category: 'Spices'             },
  { label: 'Cinnamon (Dalchini)', canonical: 'Cinnamon',                category: 'Spices'             },
  { label: 'Bay Leaves (Tejpatta)',canonical:'Bay Leaves',              category: 'Spices'             },
  { label: 'Star Anise',          canonical: 'Star Anise',              category: 'Spices'             },
  { label: 'Fennel Seeds (Saunf)',canonical: 'Fennel Seeds',            category: 'Spices'             },
  { label: 'Carom Seeds (Ajwain)',canonical: 'Carom Seeds (Ajwain)',    category: 'Spices'             },
  { label: 'Fenugreek Seeds',     canonical: 'Fenugreek Seeds',         category: 'Spices'             },
  { label: 'Dry Red Chilli',      canonical: 'Dry Red Chilli',          category: 'Spices'             },
  { label: 'Tamarind (Imli)',     canonical: 'Tamarind',                category: 'Spices'             },
  { label: 'Amchur (Dry Mango)',  canonical: 'Amchur (Dry Mango Powder)',category:'Spices'             },
  { label: 'Chaat Masala',        canonical: 'Chaat Masala',            category: 'Spices'             },
  { label: 'Sambhar Masala',      canonical: 'Sambhar Masala',          category: 'Spices'             },
  { label: 'Pav Bhaji Masala',    canonical: 'Pav Bhaji Masala',        category: 'Spices'             },
]

export const INGREDIENT_GROUP_ORDER = ['Staples', 'Fresh & Vegetables', 'Dairy', 'Non-Veg', 'Spices']
